<?xml version="1.0"?>
<package format="2">
  <name>dualsense_driver</name>
  <version>0.0.0</version>
  <description>The dualsense_driver package</description>

  <maintainer email="pythagora.yoshimoto@gmail.com">HansRobo</maintainer>

  <license>Apache 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>rcl_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
